version: '2.0'
services:
  chatgpt-on-wechat:
    image: hyqskevin/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    environment:
      OPEN_AI_API_KEY: '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'
      MODEL: 'gpt-3.5-turbo-16k'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["雪球", "@雪球"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[雪球] "'
      GROUP_CHAT_PREFIX: '["雪球", "@雪球"]'
      GROUP_NAME_WHITE_LIST: '["有趣人类研究中心（核心）", "造八米奇妙妙屋", "🌟【甬尚青年】1️⃣3️⃣", "🌟【甬尚青年】1️⃣2️⃣", "🌟【甬尚青年】1️⃣1️⃣", "🌟【甬尚青年】🔟", "🌟🌟🌟【造作星期八】9️⃣", "🌟🌟🌟【造作星期八】8️⃣", "🌟🌟🌟【造作星期八】7️⃣", "🌟🌟🌟【造作星期八】6️⃣", "🌟🌟🌟【造作星期八】5️⃣", "🌟🌟🌟【造作星期八】4️⃣", "🌟🌟🌟【造作星期八】3️⃣", "🌟🌟🌟【造作星期八】2️⃣", "🌟🌟🌟【造作星期八】1️⃣"]'
      GROUP_CHAT_IN_ONE_SESSION": '["有趣人类研究中心（核心）", "造八米奇妙妙屋", "🌟【甬尚青年】1️⃣3️⃣", "🌟【甬尚青年】1️⃣2️⃣", "🌟【甬尚青年】1️⃣1️⃣", "🌟【甬尚青年】🔟", "🌟🌟🌟【造作星期八】9️⃣", "🌟🌟🌟【造作星期八】8️⃣", "🌟🌟🌟【造作星期八】7️⃣", "🌟🌟🌟【造作星期八】6️⃣", "🌟🌟🌟【造作星期八】5️⃣", "🌟🌟🌟【造作星期八】4️⃣", "🌟🌟🌟【造作星期八】3️⃣", "🌟🌟🌟【造作星期八】2️⃣", "🌟🌟🌟【造作星期八】1️⃣"]' 
      IMAGE_CREATE_PREFIX: '["画", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'
      LINKAI_API_KEY: ''
      LINKAI_APP_CODE: ''
      REPLICATE_API_TOKEN: 'r8_2cWyZdsmb6brTofHbmlfnTodOSRSEZk2mQEYd'
